version: '3.8'

services:
  db:
    image: postgres
    container_name: yeet-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    container_name: yeet-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: db
      DB_DATABASE: postgres
    depends_on:
      - db

  frontend:
    container_name: yeet-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:3000
